/**
 * The orchestration layer that ties the engine together for the CLI:
 *
 *   Finding ──▶ ladderFinding() ──▶ LadderResult ──▶ buildBundle() ──▶ EvidenceBundle
 *
 * Provider ladders (registered in the registry) do the real probing; this
 * module routes a finding to its ladder, handles the "no ladder for this
 * provider" case, and assembles + renders the evidence bundle. It performs no
 * network I/O of its own.
 */

import { detectKey } from "./detect.js";
import { EvidenceBundle, Finding, LadderResult, Verdict } from "./models.js";
import { getLadder } from "./providers/registry.js";
import type { Consent } from "./safety.js";
import "./providers/index.js"; // populate the registry (import side-effects)

/**
 * Run the capability ladder for a single finding.
 *
 * Routes by the finding's `detectorName`. If no ladder is registered for the
 * provider, returns an `N/A` LadderResult (never throws for that reason) so a
 * mixed batch still produces a complete bundle. A `ScopeRequired` thrown by a
 * ladder (laddering with no authorized scope) propagates to the caller, which
 * maps it to the documented exit code.
 */
export async function ladderFinding(finding: Finding, consent: Consent): Promise<LadderResult> {
  const ladder = getLadder(finding.detectorName);
  if (ladder === undefined) {
    return new LadderResult({
      finding,
      provider: finding.detectorName || "unknown",
      verdict: Verdict.NA,
      authorizedScope: consent.authorizedScope ?? "",
    });
  }
  return ladder(finding, consent);
}

/**
 * Build a Finding from a bare `--key`, inferring its detector by shape.
 * `detectorOverride` (from `--detector`) wins over auto-detection.
 */
export function findingFromKey(key: string, detectorOverride?: string | null): Finding {
  const detector = detectorOverride?.trim() || detectKey(key)?.detector || "generic";
  return new Finding({ detectorName: detector, verified: false, raw: key });
}

/** Assemble an evidence bundle from ladder results. */
export function buildBundle(
  results: LadderResult[],
  consent: Consent,
  toolVersion: string,
  now: number,
): EvidenceBundle {
  // The attestation holds unless a gated probe was actually exercised (a rung
  // that ran, succeeded, and was not blocked).
  const stateChanged = results.some((r) =>
    r.rungs.some((rung) => rung.tier === "gated" && rung.success && !rung.blocked),
  );
  return new EvidenceBundle({
    authorizedScope: consent.authorizedScope ?? "",
    toolVersion,
    results,
    createdAt: now,
    noStateChanged: !stateChanged,
  });
}

/** Render a ladder result as a compact, human-readable block. */
export function renderLadderText(result: LadderResult): string {
  const lines: string[] = [];
  const v = result.verdict;
  lines.push(`${verdictGlyph(v)} ${v}  ${result.provider}  (${result.finding.redacted})`);
  for (const rung of result.rungs) {
    const mark = rung.blocked ? "🔒" : rung.success ? "✓" : "·";
    const tier = rung.tier === "gated" ? " [gated]" : "";
    lines.push(`    ${mark} ${rung.name}${tier} — ${rung.detail}`);
  }
  return lines.join("\n");
}

/** Render the full evidence bundle as Markdown (the human report). */
export function renderBundleMarkdown(bundle: EvidenceBundle): string {
  const pub = bundle.toPublic();
  const out: string[] = [];
  out.push("# vtx-recon evidence bundle");
  out.push("");
  out.push(`- **Tool:** ${pub.tool} v${pub.tool_version}`);
  out.push(`- **Authorized scope:** \`${pub.authorized_scope || "(none)"}\``);
  out.push(`- **Generated:** ${pub.created_at_iso}`);
  out.push(
    `- **Attestation:** ${
      pub.no_state_changed_attestation
        ? "No state was changed and no functionality was exercised beyond read-only probes."
        : "⚠️ A gated probe was exercised under consent — see PROVEN findings below."
    }`,
  );
  out.push("");
  for (const r of pub.results) {
    out.push(`## ${r.verdict} — ${r.provider}`);
    out.push("");
    out.push(`- **Credential:** \`${r.finding.redacted}\` (detector: ${r.finding.detector_name})`);
    out.push(`- **Verified by TruffleHog:** ${r.finding.verified}`);
    out.push("");
    out.push("| Rung | Tier | Result | Detail |");
    out.push("| :--- | :--- | :----- | :----- |");
    for (const rung of r.rungs) {
      const res = rung.blocked ? "blocked 🔒" : rung.success ? "✓" : "—";
      out.push(`| ${rung.name} | ${rung.tier} | ${res} | ${escapePipes(rung.detail)} |`);
    }
    out.push("");
  }
  out.push("---");
  out.push("");
  out.push(
    "_Generated by vtx-recon for authorized security testing only. " +
      "Secrets are redacted. See TERMS.md._",
  );
  return out.join("\n");
}

function verdictGlyph(v: Verdict): string {
  switch (v) {
    case Verdict.PROVEN:
      return "🔴";
    case Verdict.VALID:
      return "🟡";
    case Verdict.DENIED:
      return "⚪";
    default:
      return "·";
  }
}

function escapePipes(s: string): string {
  return s.replace(/\|/g, "\\|");
}
